fixed up vmrun for unicode

diff --git a/bin/mod7tests b/bin/mod7tests
--- a/bin/mod7tests
+++ b/bin/mod7tests
@@ -1,9 +1,9 @@
-#!/bin/bash
+#!/bin/bash 
 # 
-# Purpose: runs tests from .vo files
+# Purpose: runs tests from mod 7 test code. 
 # 
 
-## Usage: votests
+## Usage: mod7tests
 ## 
 ## 
 ## 
@@ -11,63 +11,89 @@
 ## author: rab
 ## date:  Mon Jan 30 16:04:53 EST 2023
 
-
+# TODO for non-roger folks using this: update these dirs! :)
 BASEDIR=/h/rburto03/106/student-2023s
 
 SVMDIR=$BASEDIR/src/svm
 UFTDIR=$BASEDIR/src/uft
 TESTDIR=$BASEDIR/tests/tests07
 
+build () {
+    cd $SVMDIR
+    make 
+    if [[ "$?" -ne "0" ]]; then
+        echo "Exiting on compilation failure."
+        exit 1
+    fi
 
-cd $SVMDIR
-make > /dev/null
-if [[ "$?" -ne "0" ]]; then
-    echo "Exiting on compilation failure."
-    exit 1
-fi
+    cd $UFTDIR
+    make 
+    if [[ "$?" -ne "0" ]]; then
+        echo "Exiting on compilation failure."
+        exit 1
+    fi
+}
 
-cd $UFTDIR
-make > /dev/null
-if [[ "$?" -ne "0" ]]; then
-    echo "Exiting on compilation failure."
-    exit 1
-fi
+numtests=0
+numfail=0
+FAILING=1
 
-# run tests
+# for people wanting to make changes: $1, $2 are arguments to a function
+update_failure () { 
+    failure=$1
+    testname=$2
+    out=$3
+    if [[ "$failure" -ne "0" ]]; then 
+        >&2 echo "Failed test $testname"
+        >&2 echo "Output: "
+        >&2 echo "$out"
+    fi
+    numfail=$((numfail + $failure))
+}
+
 run_tests () {
     
-    numfail=0
 
     for file in $TESTDIR/*vo; do
-        svm $file 2>&1  | grep "pass" > /dev/null # grep returns 0 if found
-        failure=$?
-        if [[ "$failure" -ne "0" ]]; then
-            >&2 echo "Failed test $file"
-        fi
-        numfail=$((numfail + $failure))
+        numtests=$((numtests + 1))
+        out=$(svm $file 2>&1)
+        update_failure $? $file "$out"
+        echo $out | grep -Eq 'The only test passed|Both tests passed|All tests passed'
+        update_failure $? $file $out
+                                                  # grep returns 0 if found; 
+                                                  # the whole line will return
+                                                  # nonzero if not OR if 
+                                                  # svm fails
+                                                  
     done
 
 
-
-
     for file in $TESTDIR/*vs; do
-        uft vs-vo $file | svm 2>&1 | grep "pass" > /dev/null 
-        failure=$?
-        if [[ "$failure" -ne "0" ]]; then 
-            >&2 echo "Failed test $file"
-        fi
-        numfail=$((numfail + $failure))
+        numtests=$((numtests + 1))
+        out=$(uft vs-vo $file | svm 2>&1)
+        update_failure $? $file "$out"
+        echo $out | grep -Eq 'The only test passed|Both tests passed|All tests passed'
+        update_failure $? $file $out
+                                                             # this returns 0 if
+                                                             # found; line will 
+                                                             # return nonzero if
+                                                             # not OR if uft or
+                                                             # svm fail
+        update_failure $? $file
+
     done
 
     if [[ "$numfail" -eq "0" ]]; then 
         echo "All tests passed."
     else 
-        echo "Test failure-- comment out grep pipe and look closely"
+        numpassed=$((numtests - $numfail))
+        echo "$numpassed / $numtests tests passed. \
+See above output for details."
     fi
 }
 
 main () {
-
+    build
     run_tests
 }
 
