pre-presentation: parsing on tailcall needs to be idempotent. fix after!

diff --git a/bin/mod7tests b/bin/mod7tests
--- a/bin/mod7tests
+++ b/bin/mod7tests
@@ -16,7 +16,8 @@
 BASEDIR=/h/rburto03/106/student-2023s
 
 SVMDIR=$BASEDIR/src/svm
-TESTDIR=$BASEDIR/tests/vo_tests
+UFTDIR=$BASEDIR/src/uft
+TESTDIR=$BASEDIR/tests/tests07
 
 
 cd $SVMDIR
@@ -31,23 +32,38 @@ if [[ ! -e $BASEDIR/bin/svm ]]; then
     fi
 fi
 
+cd $UFTDIR
+
+# compile if needed
+if [[ ! -e $BASEDIR/bin/uft ]]; then
+    echo "No uft executable found; compiling..."
+    make
+    if [[ "$?" -ne "0" ]]; then
+        echo "Exiting on compilation failure."
+        exit 1
+    fi
+fi
+
 # run tests
 run_tests () {
     
     pass=0
 
-    for file in $TESTDIR/to-fail/*; do
-        svm $file 2>&1 | grep "fail" > /dev/null # grep returns 0 if found
+    for file in $TESTDIR/*vo; do
+        svm $file 2>&1  | grep -v "fail" > /dev/null # grep returns 0 if found
         pass=$((pass + $?))
-        echo $pass
     done
 
-    for file in $TESTDIR/to-pass/*; do
-        svm $file | grep -v "fail" > /dev/null
-        pass=$((pass + $?))
-    done
+
+    # for file in $TESTDIR/*vs; do
+    #     uft vs-vo $file | svm $file 2>&1 # | grep -v "fail" > /dev/null # grep returns 0 if found
+    #     pass=$((pass + $?))
+    # done
+
     if [[ "$pass" -eq "0" ]]; then 
         echo "All tests passed."
+    else 
+        echo "Test failure-- comment out grep pipe and look closely"
     fi
 }
 
