add timestamp test to run-fo-predef

diff --git a/bin/run-fo-with-predef b/bin/run-fo-with-predef
--- a/bin/run-fo-with-predef
+++ b/bin/run-fo-with-predef
@@ -13,7 +13,10 @@ if [[ $flavor = hox ]]; then
 fi
 
 if [[ ! -r "$PREDEF" ]]; then
-  echo "Cannot run until $PREDEF is built.  Try making 'predef' in vscheme dir"
+  echo "Cannot run until $PREDEF is built.  Try making 'predef' in vscheme dir."
+  exit 1
+elif [[ "$BIN/uft" -nt "$PREDEF" ]]; then
+  echo 'UFT is newer than compiled predefined functions. `make predef` in vscheme dir."
   exit 1
 fi
 
@@ -24,7 +27,7 @@ case $# in
   *) cat "$@" ;;
 esac | 
 fgrep -v  'check-error' |
-uft $flavor-vo |
-svm $PREDEF -
+"$BIN/uft" $flavor-vo |
+"$BIN/svm" $PREDEF -
 
 exit $?
