final touches on some testing; we'll need diffs with some of the custom failing tests like overflow. to bed.

diff --git a/tests/test-template b/tests/test-template
--- a/tests/test-template
+++ b/tests/test-template
@@ -12,7 +12,7 @@
 ## date:  Sun Mar 12 03:30:21 EDT 2023
 
 
-BASEDIR=/Users/rogerburtonpatel/home/tufts/comp/cs106
+BASEDIR=$DIR106
 
 SVMDIR=$BASEDIR/src/svm
 UFTDIR=$BASEDIR/src/uft
@@ -25,9 +25,10 @@ build ()
     target="$1"
     cd "$BASEDIR/src/$target"
 
-    make | grep -v "Nothing to be done" # silences already-built make output
-    if [[ "$?" -ne "1" ]]; then
-        echo "Exiting on compilation failure."
+    output=`make 2>&1`
+    if [[ "$?" -ne "0" ]]; then
+        echo $output
+        echo "Exiting on $target compilation failure."
         exit 1
     fi
 
